spring.application.name=ai-payroll-backend
server.port=3000

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_payroll
spring.datasource.username=postgres
spring.datasource.password=Jayeshjain7015.
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
